6	Demographic
C	Condition
D	Drug
O	Observation
M	Measurement
P	Procedure
4	Device
9	Location
N	Negation
Q	Qualifier
T	Temporal
V	Value
5	Multiplier
R	Reference_point
L	Line
1	Mood
Y	Non-query-able
E	Post-eligibility
G	Pregnancy_considerations
A	v-AND
I	Informed_consent
Z	v-OR
B	Non-representable
3	Person
2	Visit
