#!/bin/bash
#SBATCH --output slurm.%N.%j.out     # STDOUT (%N: nodename, %j: job-ID)
#SBATCH --error slurm.%N.%j.err      # STDERR
#SBATCH --partition=any              # partition (queue)
#SBATCH --ntasks 64                  # number of tasks/cores
#SBATCH --mem 150000                  # memory per node in MB
#SBATCH --time 72:00:00              # total runtime of job allocation

#module load cuda/11.6

# export CONDA_ENV='/scratch/tgerla2s/miniconda3/envs/unifold/bin'
export CONDA_ENV='/scratch/tgerla2s/miniconda3/envs/xtrimomultimer/bin'
export DOWNLOAD_DIR='/scratch/tgerla2s/alphafold2/download'
export TOOLS_DIR='/scratch/tgerla2s/alphafold2/tools'

export jackhmmer='/scratch/tgerla2s/miniconda3/envs/af2/bin/jackhmmer'

# https://elearning.bits.vib.be/courses/alphafold/lessons/alphafold-on-the-hpc/topic/alphafold-outputs/?sfwd-courses=alphafold&sfwd-lessons=alphafold-on-the-hpc&sfwd-topic=alphafold-outputs
eval "$(conda shell.bash hook)"

# FOLDER="ENaC_hum_3_a_b_g_multi"
# PREDICT_NAME="P37088"

mkdir -p "/scratch/tgerla2s/pdb_predictions/$FOLDER/unifold"

export output_dir="/scratch/tgerla2s/pdb_predictions/$FOLDER/unifold/"
export fasta_path="fasta_source/$FOLDER/$PREDICT_NAME.fasta"

START_DATE=`date`
conda activate unifold

echo "Starting homogeneous searching..."
python ../unifold/Uni-Fold/unifold/homo_search.py \
    --fasta_path="fasta_source/$FOLDER/$PREDICT_NAME.fasta" \
    --max_template_date=`date +"%Y-%m-%d"` \
    --output_dir=$output_dir  \
    --uniref90_database_path=$DOWNLOAD_DIR/uniref90/uniref90.fasta \
    --mgnify_database_path=$DOWNLOAD_DIR/mgnify/mgy_clusters.fa \
    --bfd_database_path=$DOWNLOAD_DIR/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
    --uniclust30_database_path=$DOWNLOAD_DIR/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
    --uniprot_database_path=$DOWNLOAD_DIR/uniprot/uniprot.fasta \
    --pdb_seqres_database_path=$DOWNLOAD_DIR/pdb_seqres/pdb_seqres.txt \
    --template_mmcif_dir=$DOWNLOAD_DIR/pdb_mmcif/mmcif_files \
    --obsolete_pdbs_path=$DOWNLOAD_DIR/pdb_mmcif/obsolete.dat \
    --jackhmmer_binary_path=$CONDA_ENV/jackhmmer \
    --hhblits_binary_path=$CONDA_ENV/hhblits \
    --hhsearch_binary_path=$CONDA_ENV/hhsearch \
    --hmmsearch_binary_path=$CONDA_ENV/hmmsearch \
    --hmmbuild_binary_path=$CONDA_ENV/hmmbuild \
    --kalign_binary_path=$CONDA_ENV/kalign \
    --use_precomputed_msas=True

echo "Starting prediction..."
fasta_file=$(basename $fasta_path)
target_name=${fasta_file%.fa*}
python ../unifold/Uni-Fold/unifold/inference.py \
	--model_name="multimer_ft" \
	--param_path="../unifold/Uni-Fold/multimer.unifold.pt" \
	--data_dir=$output_dir \
	--target_name=$target_name \
    --model_device="cpu"
	--output_dir=$output_dir 


END_DATE=`date`
echo "Job started $START_DATE, finished at $END_DATE"