[entities]
!CONCEPTS
	Scope
	Person
	Condition
	Drug
	Observation
	Measurement
	Procedure
	Device
	Visit
!ANNOTATION
	Negation
	Qualifier
	Temporal
	Value
	Multiplier
	Reference_point
	Line
	Mood
!ERROR
	Non-query-able
	Post-eligibility
	Pregnancy_considerations
	Competing_trial
	Informed_consent
	Intoxication_considerations
	Non-representable

[events]

[relations]
OR   Arg1:<ENTITY>, Arg2:<ENTITY>, <REL-TYPE>:symmetric-transitive
AND Arg1:<ANY>, Arg2:<ANY>
subsumes Arg1:<ANY>, Arg2:<ANY>
multi Arg1:<ANY>, Arg2:<ANY>
has_negation Arg1:<ANY>, Arg2:Negation
has_multiplier Arg1:<ANY>, Arg2:Multiplier
has_qualifier Arg1:<ANY>, Arg2:Qualifier
has_value Arg1:<ANY>, Arg2:Value
has_temporal Arg1:<ANY>, Arg2:Temporal|Observation
has_index Arg1:<ANY>, Arg2:Reference_point
has_mood Arg1:<ANY>, Arg2:Mood
has_context Arg1:<ANY>, Arg2:Observation
has_scope Arg1:<ANY>, Arg2:Scope
<OVERLAP>	Arg1:<ANY>, Arg2:<ANY>, <OVL-TYPE>:<ANY>

[attributes]
Optional   Arg:<ANY>
 
